# Directories arguments
data_dir: "174_imgs_for_test_n_overfit"
exp_dir:  "dilation_exp_test"
out_dir:  "dilation_exp_test"

# Data arguments
img_height:   256
img_width:    512
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 3
shuffle: True
data_mode: "overfit"
save_every: 5
test_every: 5
max_to_keep: 5

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
pretrained_path: "pretrained_weights/vgg16.npy"

# Misc arguments
verbose: False

