# Directories arguments
data_dir: "full_cityscapes_res"
exp_dir:  "dilation_mobilenet"
out_dir:  "dilation_mobilenet"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 4
shuffle: True
data_mode: "experiment"
save_every: 10
test_every: 5
max_to_keep: 2
weighted_loss: True

# Models arguments
learning_rate:   9e-5
weight_decay: 0.000005
momentum: 0.9
learning_decay: 0.7
pretrained_path: "pretrained_weights/mobilenet_v1.pkl"
learning_decay_every: 10

# Misc arguments
verbose: False

