# Directories arguments
data_dir: "data_for_test_n_overfit"
exp_dir:  "fcn8s_shufflenet_exp"
out_dir:  "fcn8s_shufflenet_exp"

# Data arguments
img_height:   360
img_width:    640
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 400
batch_size: 1
shuffle: True
data_mode: "overfit"
save_every: 5
test_every: 5
max_to_keep: 5
weighted_loss: False

# Models arguments
batchnorm_enabled: True
num_groups: 3
learning_rate:   0.00001
weight_decay: 0.0
bias: 0.0
pretrained_path: "pretrained_weights/shufflenet_weights.pkl"

# Misc arguments
verbose: False

