# Directories arguments
data_dir: "full_cityscapes_res"
abs_data_dir: "/home/eren/Data/Cityscapes_Coarse/"
exp_dir:  "fcn8s_vgg16"
out_dir:  "fcn8s_vgg16"

# Data arguments
img_height:   512
img_width:    512
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 8
shuffle: True
data_mode: "experiment_tfdata"
save_every: 5
test_every: 5
max_to_keep: 2
weighted_loss: False

# Models arguments
batchnorm_enabled: True
learning_rate:   0.0001
weight_decay: 4e-5
pretrained_path: "pretrained_weights/vgg16.npy"

# Misc arguments
verbose: False

