# Directories arguments
data_dir: "data_for_test_n_overfit"
exp_dir:  "fcn8s_mobilenet_exp"
out_dir:  "fcn8s_mobilenet_exp"

# Data arguments
img_height:   360
img_width:    640
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: True
data_mode: "overfit"
save_every: 5
test_every: 5
max_to_keep: 5
weighted_loss: False

# Models arguments
batchnorm_enabled: True
learning_rate:   0.0001
weight_decay: 4e-5
bias: 0.0
pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

