# Directories arguments
data_dir: "full_cityscapes"
exp_dir:  "linknet_exp_overfit"
out_dir:  "linknet_exp_overfit"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 10
batch_size: 4
shuffle: True
data_mode: "overfit"
save_every: 5
test_every: 2
max_to_keep: 1
weighted_loss: True

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
pretrained_path: "pretrained_weights/resnet18.npy"

# Misc arguments
verbose: False

