# Directories arguments
data_dir: "data_for_test_n_overfit"
exp_dir:  "linknet_exp_overfit_5"
out_dir:  "linknet_exp_overfit_5"

# Data arguments
img_height:   256
img_width:    512
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 30
batch_size: 8
shuffle: True
data_mode: "overfit"
save_every: 5
test_every: 2
max_to_keep: 1
weighted_loss: True

# Models arguments
learning_rate:   0.005
weight_decay: 0.0002
momentum: 0.9
learning_decay: 0.00001
pretrained_path: "pretrained_weights/resnet18.npy"
learning_decay_every: 50

# Misc arguments
verbose: False

