# Directories arguments
data_dir: "174_imgs_for_test_n_overfit"
exp_dir:  "test"
out_dir:  "test"

# Data arguments
img_height:   256
img_width:    512
num_channels: 3
num_classes:  30

# Train arguments
num_epochs: 10
batch_size: 32
shuffle: False
data_mode: "overfit"
save_every: 2
test_every: 2
max_to_keep: 5

# Models arguments
learning_rate:   0.0007
weight_decay: 0.0005
pretrained_path: "pretrained_weights/vgg16.npy"

# Misc arguments
verbose: False

## Add the first layer to finetune
