# Directories arguments
data_dir: "full_cityscapes_res"
abs_data_dir: "/home/eren/Data/Cityscapes_Coarse/"
exp_dir:  "unet_resnet18_coarse"
out_dir:  "unet_resnet18_coarse"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 6
shuffle: True
data_mode: "experiment_tfdata"
save_every: 10
test_every: 10
max_to_keep: 1
weighted_loss: True
random_cropping: False

# Models arguments
batchnorm_enabled: True
learning_rate:   0.0001
weight_decay: 4e-5
bias: 0.0
pretrained_path: "pretrained_weights/resnet18.npy"

# Misc arguments
verbose: False

